### ISSUE TITLE
执行dingtalk init webpack报错

### ISSUE THREAD

**Issue by WangYang-Rex** [icepy/weex-dingtalk-cli#1]
<img width="660" alt="123" src="https://user-images.githubusercontent.com/7553998/28053208-d65d540a-6641-11e7-85c1-02a3eb3879f1.png">

**Comment by icepy** [comment]
看一下你的网络，是不是被墙了。

**Comment by icepy** [comment]
在你本地有相同名字的项目，你必须先删除。 @WangYang-Rex
