### ISSUE TITLE
该脚手架还有在维护吗？

### ISSUE THREAD

**Issue by Shruan** [icepy/weex-dingtalk-cli#2]
这个脚手架怎么在非钉钉容器的web端调试，
我使用这个脚手架时使用dev:weex在钉钉容器中可以显示正常的文本信息，
而使用dev:web在Chrome浏览器上面打开是却看不到有关于文本的所有内容，
这是什么导致的，要怎么处理才能让它可以在Chrome浏览器上调试

**Comment by Shruan** [comment]
![Uploading F128E106-FC8E-4119-9B02-F6548F59DFAA.png…]()

**Comment by Shruan** [comment]
![Uploading image.png…]()

**Comment by Shruan** [comment]
![image](https://user-images.githubusercontent.com/28869029/31587497-51622cdc-b1a8-11e7-9e6b-ebccca718fde.png)

**Comment by icepy** [comment]
@Shruan 已修复
